// <auto-generated />
using System;
using LoggingWayGrpcService.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoggingWayMaster.Migrations
{
    [DbContext(typeof(LoggingwayDbContext))]
    partial class LoggingwayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("LoggingWayGrpcService.Entities.CharacterClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_url");

                    b.Property<string>("CharName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("charname");

                    b.Property<Guid?>("ClaimBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("claim_by");

                    b.Property<DateTimeOffset>("ClaimRegistered")
                        .HasColumnType("TEXT")
                        .HasColumnName("claim_registered");

                    b.Property<string>("DataCenter")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("datacenter");

                    b.Property<string>("HomeWorld")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("homeworld");

                    b.Property<int>("LodestoneId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lodestone_id");

                    b.Property<string>("PortraitUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("portrait_url");

                    b.Property<string>("XivAuthKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("xivauthkey");

                    b.HasKey("Id");

                    b.HasIndex("ClaimBy");

                    b.HasIndex("XivAuthKey", "CharName", "DataCenter", "HomeWorld")
                        .IsUnique();

                    b.ToTable("characters_claim", (string)null);
                });

            modelBuilder.Entity("LoggingWayGrpcService.Entities.Encounter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("CfcId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cfc_id");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("UploadedBy");

                    b.ToTable("encounters", (string)null);
                });

            modelBuilder.Entity("LoggingWayGrpcService.Entities.EncounterPlayerStat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<Guid?>("Character")
                        .HasColumnType("TEXT")
                        .HasColumnName("character");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<double>("CritRate")
                        .HasColumnType("REAL")
                        .HasColumnName("crit_rate");

                    b.Property<double>("DirectHitRate")
                        .HasColumnType("REAL")
                        .HasColumnName("direct_hit_rate");

                    b.Property<double>("Dps")
                        .HasColumnType("REAL")
                        .HasColumnName("dps");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("duration_seconds");

                    b.Property<long>("EncounterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("encounter_id");

                    b.Property<long>("FirstTimestamp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("first_timestamp");

                    b.Property<double>("Hps")
                        .HasColumnType("REAL")
                        .HasColumnName("hps");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("job_id");

                    b.Property<long>("LastTimestamp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_timestamp");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("player_id");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("player_name");

                    b.Property<long>("TotalCrits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_crits");

                    b.Property<long>("TotalDamage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_damage");

                    b.Property<long>("TotalDirectHits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_direct_hits");

                    b.Property<long>("TotalHealing")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_healing");

                    b.Property<long>("TotalHits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_hits");

                    b.Property<double>("TotalPScore")
                        .HasColumnType("REAL")
                        .HasColumnName("total_pscore");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("Character");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("EncounterId", "PlayerId")
                        .IsUnique();

                    b.ToTable("encounter_player_stats", (string)null);
                });

            modelBuilder.Entity("LoggingWayGrpcService.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Banned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("banned");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LoggingWayGrpcService.Entities.CharacterClaim", b =>
                {
                    b.HasOne("LoggingWayGrpcService.Entities.User", "Owner")
                        .WithMany("Characters")
                        .HasForeignKey("ClaimBy");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LoggingWayGrpcService.Entities.Encounter", b =>
                {
                    b.HasOne("LoggingWayGrpcService.Entities.User", "Uploader")
                        .WithMany("Encounters")
                        .HasForeignKey("UploadedBy");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("LoggingWayGrpcService.Entities.EncounterPlayerStat", b =>
                {
                    b.HasOne("LoggingWayGrpcService.Entities.CharacterClaim", "CharacterClaim")
                        .WithMany("PlayerStats")
                        .HasForeignKey("Character");

                    b.HasOne("LoggingWayGrpcService.Entities.Encounter", "Encounter")
                        .WithMany("PlayerStats")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoggingWayGrpcService.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy");

                    b.Navigation("CharacterClaim");

                    b.Navigation("Encounter");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("LoggingWayGrpcService.Entities.CharacterClaim", b =>
                {
                    b.Navigation("PlayerStats");
                });

            modelBuilder.Entity("LoggingWayGrpcService.Entities.Encounter", b =>
                {
                    b.Navigation("PlayerStats");
                });

            modelBuilder.Entity("LoggingWayGrpcService.Entities.User", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Encounters");
                });
#pragma warning restore 612, 618
        }
    }
}
